name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Install dependencies
    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y cmake g++ lcov python3-pip
        pip install gcovr

    # 3. Clone and build Google Test
    - name: Build Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    # 4. Build the project
    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    # 5. Prepare test folder
    - name: Create test folder
      run: |
        mkdir -p build/test_folder
        touch build/test_folder/song1.mp3
        touch build/test_folder/song2.mp3
        touch build/test_folder/song3.mp3

    # 6. Run unit tests
    - name: Run unit tests
      run: |
        cd build
        ctest --output-on-failure

    # 7. Generate code coverage report
    - name: Generate coverage report
      run: |
        cd build
        cd ..
        gcovr -r . --filter src/ --html --html-details -o reports/coverage.html

    # 8. Upload coverage report
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: reports/coverage_cicd.html


    # 9. Fail the job if unit tests fail
    - name: Fail the job if unit tests fail
      if: ${{ failure() }}
      run: exit 1
